/**
 * Single source of truth cho version + changelog của extension.
 *
 * Quy tắc bump version (semver-like):
 *   - MAJOR (x.0.0): breaking change về protocol/storage hoặc đổi cấu trúc lớn
 *   - MINOR (0.x.0): thêm action mới (SYNC_BILLING, INVITE_MEMBER, ...) hoặc
 *                    thay đổi UI lớn (popup redesign, scraper rewrite)
 *   - PATCH (0.0.x): fix bug, sửa selectors, tune timing/regex
 *
 * Khi bump:
 *   1. Tăng `VERSION` ở dưới
 *   2. Prepend 1 entry mới ở đầu `CHANGELOG` (most recent first)
 *   3. Build lại extension, reload trong chrome://extensions
 *
 * Cách viết 1 entry (viết như ghi chú cập nhật của hãng điện thoại, cực ngắn):
 *   - `title`: tên mục, 1-3 từ, không có dấu hai chấm ("Mời thành viên",
 *     "Mua suất", "Ổn định", "Bảo mật")
 *   - `note`: ĐÚNG MỘT CÂU, tối đa ~90 ký tự, nói kết quả user thấy được
 *   - Không liệt kê gạch đầu dòng, không kể nguyên nhân kỹ thuật, không ghi
 *     số test, tên file, tên hàm, tên selector, con số thời gian chờ
 *   - Gộp nhiều thay đổi nhỏ cùng nhóm thành một câu chung
 *
 * Manifest tự đọc VERSION từ file này — KHÔNG cần sửa manifest.ts.
 * Popup chỉ mở sẵn mục mới nhất, các bản cũ thu gọn còn 1 dòng và
 * chỉ hiện 8 mục đầu, phần còn lại nằm sau nút "Xem thêm".
 */

export const VERSION = "0.15.9";

export type ChangelogEntry = {
  version: string;
  date: string; // YYYY-MM-DD
  kind: "feature" | "fix" | "chore";
  /** Tên mục ngắn, 1-3 từ. */
  title: string;
  /** Một câu duy nhất, hiển thị khi user expand. */
  note: string;
};

export const KIND_COLOR: Record<ChangelogEntry["kind"], string> = {
  feature: "#10b981",
  fix: "#f59e0b",
  chore: "#6b7280",
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.15.9",
    date: "2026-09-03",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đổi tab xong phải thấy đúng danh sách mới quét, và trang hết bị ghim.",
  },
  {
    version: "0.15.8",
    date: "2026-09-03",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ hết đọc nhầm danh sách của tab vừa rời, không còn treo rồi báo hỏng.",
  },
  {
    version: "0.15.7",
    date: "2026-09-01",
    kind: "fix",
    title: "Giao diện mới",
    note: "Bắt kịp giao diện ChatGPT mới, mua suất và đổi vai trò hết bấm nhầm chỗ.",
  },
  {
    version: "0.15.6",
    date: "2026-09-01",
    kind: "fix",
    title: "Gỡ Canva",
    note: "Gỡ và thu hồi lời mời Canva xong thì nhật ký báo đúng, hết báo thất bại oan.",
  },
  {
    version: "0.15.5",
    date: "2026-09-01",
    kind: "feature",
    title: "Thao tác Canva",
    note: "Canva đổi được vai trò và gửi lại lời mời, giống hệt bên ChatGPT.",
  },
  {
    version: "0.15.4",
    date: "2026-09-01",
    kind: "fix",
    title: "Gỡ Canva",
    note: "Gỡ thành viên và thu hồi lời mời Canva đi đúng nút thùng rác của Canva.",
  },
  {
    version: "0.15.3",
    date: "2026-09-01",
    kind: "fix",
    title: "Mời Canva",
    note: "Tab Canva hết nhận lệnh thì extension tự tải lại, không cần bấm F5 tay.",
  },
  {
    version: "0.15.2",
    date: "2026-09-01",
    kind: "fix",
    title: "Mời Canva",
    note: "Lệnh mời Canva không còn đứng im hay chết sớm khi trang chưa vẽ xong.",
  },
  {
    version: "0.15.1",
    date: "2026-09-01",
    kind: "fix",
    title: "Canva",
    note: "Chạy được cả khi trang Canva đang để tiếng Anh.",
  },
  {
    version: "0.15.0",
    date: "2026-09-01",
    kind: "feature",
    title: "Canva",
    note: "Thêm khoá team Canva để một Chrome chạy được cả ChatGPT lẫn Canva.",
  },
  {
    version: "0.14.5",
    date: "2026-08-30",
    kind: "fix",
    title: "Mời thành viên",
    note: "Lời mời không còn đứng hình khi ChatGPT chậm phản hồi.",
  },
  {
    version: "0.14.4",
    date: "2026-08-30",
    kind: "fix",
    title: "Mời thành viên",
    note: "Lệnh mời chạy gọn hơn, không còn hỏng vì quá thời gian chờ.",
  },
  {
    version: "0.14.3",
    date: "2026-08-28",
    kind: "fix",
    title: "Đếm suất",
    note: "Số suất được đếm tại chỗ và báo về bảng điều khiển sau mỗi lần mời.",
  },
  {
    version: "0.14.2",
    date: "2026-08-28",
    kind: "fix",
    title: "Đồng bộ",
    note: "Lời mời đang chờ không còn bị báo nhầm là đã tham gia.",
  },
  {
    version: "0.14.1",
    date: "2026-08-28",
    kind: "fix",
    title: "Mua suất",
    note: "Mua suất ổn định hơn khi trang ChatGPT nạp chậm.",
  },
  {
    version: "0.14.0",
    date: "2026-08-28",
    kind: "feature",
    title: "Mời thành viên",
    note: "Nhiều lệnh cùng một workspace được gộp lại, chạy gọn trong một lượt.",
  },
  {
    version: "0.13.21",
    date: "2026-08-28",
    kind: "fix",
    title: "Mời thành viên",
    note: "Kết quả mời được ghi nhận chính xác hơn.",
  },
  {
    version: "0.13.20",
    date: "2026-08-28",
    kind: "fix",
    title: "Mua suất",
    note: "Mua bù suất hoạt động trở lại sau khi ChatGPT đổi giao diện.",
  },
  {
    version: "0.13.19",
    date: "2026-08-26",
    kind: "fix",
    title: "Mua suất",
    note: "Mua xong nhận biết ngay, không mua lại lần hai.",
  },
  {
    version: "0.13.18",
    date: "2026-08-26",
    kind: "fix",
    title: "Mua suất",
    note: "Số suất vừa mua luôn được ghi nhận đúng.",
  },
  {
    version: "0.13.17",
    date: "2026-08-26",
    kind: "fix",
    title: "Mua suất",
    note: "Gặp báo lỗi của ChatGPT thì kiểm tra lại rồi mới mua tiếp.",
  },
  {
    version: "0.13.16",
    date: "2026-08-26",
    kind: "fix",
    title: "Mua suất",
    note: "Kiểm tra số suất sau khi mua nhanh hơn.",
  },
  {
    version: "0.13.15",
    date: "2026-08-26",
    kind: "fix",
    title: "Mua suất",
    note: "Mua xong là mời được ngay, không còn báo quá thời gian chờ.",
  },
  {
    version: "0.13.14",
    date: "2026-08-26",
    kind: "fix",
    title: "Chu kỳ thanh toán",
    note: "Ngày gia hạn lấy đúng theo trang ChatGPT.",
  },
  {
    version: "0.13.13",
    date: "2026-08-26",
    kind: "feature",
    title: "Hiệu năng",
    note: "Mời nhanh hơn khi workspace còn dư suất.",
  },
  {
    version: "0.13.12",
    date: "2026-08-26",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ hàng loạt chạy nhanh hơn.",
  },
  {
    version: "0.13.11",
    date: "2026-08-26",
    kind: "feature",
    title: "Đếm suất",
    note: "Đọc số suất nhanh hơn trước.",
  },
  {
    version: "0.13.10",
    date: "2026-08-24",
    kind: "chore",
    title: "Bảo trì",
    note: "Tab ChatGPT do extension mở sẽ tự đóng khi để không lâu.",
  },
  {
    version: "0.13.9",
    date: "2026-08-24",
    kind: "fix",
    title: "Mua suất",
    note: "Mua xong mới mời tiếp, hai việc không còn chồng nhau.",
  },
  {
    version: "0.13.8",
    date: "2026-08-24",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Gỡ thành viên hoạt động trở lại sau khi ChatGPT đổi giao diện.",
  },
  {
    version: "0.13.7",
    date: "2026-08-24",
    kind: "feature",
    title: "Mua suất",
    note: "Thiếu suất cho lời mời đang chờ thì tự mua bù sau mỗi lần đồng bộ.",
  },
  {
    version: "0.13.6",
    date: "2026-08-24",
    kind: "fix",
    title: "Mời thành viên",
    note: "Không còn báo thiếu suất khi workspace vẫn còn chỗ.",
  },
  {
    version: "0.13.5",
    date: "2026-08-24",
    kind: "fix",
    title: "Mua suất",
    note: "Mua đủ suất cho cả những lời mời đang chờ.",
  },
  {
    version: "0.13.4",
    date: "2026-08-24",
    kind: "feature",
    title: "Mời thành viên",
    note: "Mời nhanh hơn khi workspace còn dư chỗ.",
  },
  {
    version: "0.13.3",
    date: "2026-08-24",
    kind: "fix",
    title: "Đồng bộ",
    note: "Mỗi lần đồng bộ đều cập nhật số suất thật về bảng điều khiển.",
  },
  {
    version: "0.13.2",
    date: "2026-08-24",
    kind: "fix",
    title: "Đếm suất",
    note: "Đếm suất ổn định hơn khi trang nạp chậm.",
  },
  {
    version: "0.13.1",
    date: "2026-08-23",
    kind: "fix",
    title: "Đếm suất",
    note: "Đếm suất chính xác hơn.",
  },
  {
    version: "0.13.0",
    date: "2026-08-22",
    kind: "feature",
    title: "Mời thành viên",
    note: "Kiểm số suất trước khi mời, thiếu thì tự mua bù.",
  },
  {
    version: "0.12.0",
    date: "2026-08-22",
    kind: "feature",
    title: "Mua suất",
    note: "Mua suất ngay trên trang thành viên theo giao diện mới của ChatGPT.",
  },
  {
    version: "0.11.9",
    date: "2026-08-21",
    kind: "fix",
    title: "Thu hồi lời mời",
    note: "Thu hồi lời mời chính xác hơn.",
  },
  {
    version: "0.11.8",
    date: "2026-08-21",
    kind: "feature",
    title: "Gỡ thành viên",
    note: "Người chưa tham gia thì thu hồi lời mời thay vì báo không tìm thấy.",
  },
  {
    version: "0.11.7",
    date: "2026-08-21",
    kind: "fix",
    title: "Ổn định",
    note: "Đổi vai trò, đổi loại suất và thu hồi lời mời báo kết quả chính xác hơn.",
  },
  {
    version: "0.11.6",
    date: "2026-08-18",
    kind: "fix",
    title: "Ổn định",
    note: "Các lệnh quản lý thành viên hoạt động trở lại sau khi ChatGPT đổi giao diện.",
  },
  {
    version: "0.11.5",
    date: "2026-08-13",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Kết quả gỡ thành viên đáng tin hơn.",
  },
  {
    version: "0.11.4",
    date: "2026-08-13",
    kind: "fix",
    title: "Mời thành viên",
    note: "Xác minh lời mời nhanh hơn.",
  },
  {
    version: "0.11.3",
    date: "2026-08-12",
    kind: "fix",
    title: "Mời thành viên",
    note: "Mời thành công không còn bị báo hỏng rồi hoàn tiền.",
  },
  {
    version: "0.11.2",
    date: "2026-08-12",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Không còn báo đã gỡ khi thành viên vẫn còn trong workspace.",
  },
  {
    version: "0.11.1",
    date: "2026-08-04",
    kind: "fix",
    title: "Mời thành viên",
    note: "Mời xong không còn bị báo hỏng nhầm.",
  },
  {
    version: "0.11.0",
    date: "2026-08-04",
    kind: "feature",
    title: "Riêng tư",
    note: "Thêm lệnh xuất và xoá dữ liệu của một thành viên, mặc định tắt.",
  },
  {
    version: "0.10.2",
    date: "2026-08-04",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Chặn nhầm lẫn giữa gỡ thành viên và xoá dữ liệu.",
  },
  {
    version: "0.10.1",
    date: "2026-08-01",
    kind: "fix",
    title: "Mời thành viên",
    note: "Mất kết nối giữa chừng cũng không còn báo hỏng oan.",
  },
  {
    version: "0.10.0",
    date: "2026-07-27",
    kind: "feature",
    title: "Bảo trì",
    note: "Tab ChatGPT để không sẽ tự đóng sau một thời gian.",
  },
  {
    version: "0.9.31",
    date: "2026-07-26",
    kind: "fix",
    title: "Hoá đơn",
    note: "Đếm đúng số suất trên hoá đơn có nhiều dòng cộng dồn.",
  },
  {
    version: "0.9.30",
    date: "2026-07-25",
    kind: "fix",
    title: "Hoá đơn",
    note: "Đọc được đầy đủ chi tiết hoá đơn.",
  },
  {
    version: "0.9.29",
    date: "2026-07-25",
    kind: "fix",
    title: "Hoá đơn",
    note: "Mở chi tiết hoá đơn đáng tin hơn.",
  },
  {
    version: "0.9.28",
    date: "2026-07-25",
    kind: "fix",
    title: "Hoá đơn",
    note: "Đọc được hoá đơn ở mọi cách viết của ChatGPT.",
  },
  {
    version: "0.9.27",
    date: "2026-07-25",
    kind: "fix",
    title: "Hoá đơn",
    note: "Đọc chi tiết hoá đơn ổn định hơn.",
  },
  {
    version: "0.9.26",
    date: "2026-07-25",
    kind: "fix",
    title: "Hoá đơn",
    note: "Trang thanh toán không còn trống khi đọc hoá đơn thất bại.",
  },
  {
    version: "0.9.25",
    date: "2026-07-25",
    kind: "fix",
    title: "Chu kỳ thanh toán",
    note: "Lấy đúng chu kỳ hiện tại của workspace.",
  },
  {
    version: "0.9.24",
    date: "2026-07-22",
    kind: "fix",
    title: "Đồng bộ",
    note: "Workspace chưa có lời mời nào không còn bị báo lỗi.",
  },
  {
    version: "0.9.23",
    date: "2026-07-22",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Gỡ thành viên nhanh hơn.",
  },
  {
    version: "0.9.22",
    date: "2026-07-21",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Chỉ báo xong khi thành viên thật sự biến mất khỏi danh sách.",
  },
  {
    version: "0.9.21",
    date: "2026-07-21",
    kind: "fix",
    title: "Đồng bộ",
    note: "Không còn báo nhầm đang chờ tham gia.",
  },
  {
    version: "0.9.20",
    date: "2026-07-15",
    kind: "fix",
    title: "Ổn định",
    note: "Báo rõ khi phiên đăng nhập ChatGPT hỏng.",
  },
  {
    version: "0.9.19",
    date: "2026-07-15",
    kind: "fix",
    title: "Mời thành viên",
    note: "Chờ ChatGPT sẵn sàng rồi mới gửi lời mời ngoài tên miền.",
  },
  {
    version: "0.9.18",
    date: "2026-07-15",
    kind: "fix",
    title: "Đồng bộ",
    note: "Kiểm tra đã tham gia chạy nhanh hơn.",
  },
  {
    version: "0.9.17",
    date: "2026-07-15",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ không còn sót thành viên.",
  },
  {
    version: "0.9.16",
    date: "2026-07-14",
    kind: "fix",
    title: "Đồng bộ",
    note: "Email đang chờ không còn bị báo là không tìm thấy.",
  },
  {
    version: "0.9.15",
    date: "2026-07-13",
    kind: "fix",
    title: "Đồng bộ",
    note: "Email vừa tham gia không còn bị xoá oan.",
  },
  {
    version: "0.9.14",
    date: "2026-07-13",
    kind: "fix",
    title: "Thu hồi lời mời",
    note: "Thu hồi không thành thì báo lỗi, không báo xong giả.",
  },
  {
    version: "0.9.13",
    date: "2026-07-12",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Không báo lỗi khi việc gỡ đã thành công.",
  },
  {
    version: "0.9.12",
    date: "2026-07-12",
    kind: "fix",
    title: "Hoá đơn",
    note: "Lấy đúng chu kỳ dịch vụ trên hoá đơn nhiều dòng.",
  },
  {
    version: "0.9.11",
    date: "2026-07-12",
    kind: "fix",
    title: "Hoá đơn",
    note: "Hoá đơn đầu kỳ không còn bị bỏ sót.",
  },
  {
    version: "0.9.10",
    date: "2026-07-10",
    kind: "fix",
    title: "Đồng bộ",
    note: "Người đã tham gia không còn bị báo là đang chờ.",
  },
  {
    version: "0.9.9",
    date: "2026-07-07",
    kind: "fix",
    title: "Hoá đơn",
    note: "Đọc được hoá đơn điều chỉnh suất giữa kỳ.",
  },
  {
    version: "0.9.8",
    date: "2026-07-06",
    kind: "fix",
    title: "Hoá đơn",
    note: "Mở chi tiết hoá đơn mua thêm suất đáng tin hơn.",
  },
  {
    version: "0.9.7",
    date: "2026-07-06",
    kind: "fix",
    title: "Đếm suất",
    note: "Đọc được số suất ở mọi cách hiển thị của ChatGPT.",
  },
  {
    version: "0.9.6",
    date: "2026-07-06",
    kind: "feature",
    title: "Hoá đơn",
    note: "Đọc chính xác số suất, đơn giá và chu kỳ từ chi tiết hoá đơn.",
  },
  {
    version: "0.9.5",
    date: "2026-07-06",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ hàng loạt chạy nhanh hơn trong một lượt.",
  },
  {
    version: "0.9.4",
    date: "2026-07-03",
    kind: "fix",
    title: "Đồng bộ",
    note: "Lần đồng bộ đầu tiên lấy đủ danh sách thành viên.",
  },
  {
    version: "0.9.3",
    date: "2026-06-29",
    kind: "fix",
    title: "Hiệu năng",
    note: "Nhập email khi mời nhanh hơn nhiều.",
  },
  {
    version: "0.9.2",
    date: "2026-06-29",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Không báo lỗi oan khi mạng chậm.",
  },
  {
    version: "0.9.1",
    date: "2026-06-29",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Không đánh dấu đã gỡ khi tìm nhầm ở danh sách lời mời.",
  },
  {
    version: "0.9.0",
    date: "2026-06-23",
    kind: "feature",
    title: "Giới hạn tín dụng",
    note: "Thêm lệnh đặt giới hạn tín dụng mỗi tháng cho thành viên.",
  },
  {
    version: "0.8.21",
    date: "2026-06-23",
    kind: "fix",
    title: "Hiệu năng",
    note: "Chạy nhiều lệnh liên tiếp không còn mở thêm tab.",
  },
  {
    version: "0.8.20",
    date: "2026-06-22",
    kind: "fix",
    title: "Ổn định",
    note: "Không tự đóng tab bạn đang mở.",
  },
  {
    version: "0.8.19",
    date: "2026-06-21",
    kind: "chore",
    title: "Giao diện",
    note: "Bỏ thông báo nổi trên trang ChatGPT, kết quả chỉ hiện ở bảng điều khiển.",
  },
  {
    version: "0.8.18",
    date: "2026-06-20",
    kind: "fix",
    title: "Ổn định",
    note: "Mọi lệnh chạy ổn định hơn khi trang nạp chậm.",
  },
  {
    version: "0.8.17",
    date: "2026-06-20",
    kind: "feature",
    title: "Giao diện",
    note: "Mỗi lệnh chạy xong hiện thông báo ngay trên trang ChatGPT.",
  },
  {
    version: "0.8.16",
    date: "2026-06-20",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ một tài khoản ổn định hơn.",
  },
  {
    version: "0.8.15",
    date: "2026-06-19",
    kind: "fix",
    title: "Thu hồi lời mời",
    note: "Thu hồi lời mời không còn báo không tìm thấy.",
  },
  {
    version: "0.8.14",
    date: "2026-06-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Mời email ngoài tên miền ổn định hơn.",
  },
  {
    version: "0.8.13",
    date: "2026-06-19",
    kind: "fix",
    title: "Ổn định",
    note: "Các lệnh chạy độc lập, không ảnh hưởng lẫn nhau.",
  },
  {
    version: "0.8.12",
    date: "2026-06-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Chờ cảnh báo của ChatGPT biến mất rồi mới gửi.",
  },
  {
    version: "0.8.11",
    date: "2026-06-19",
    kind: "fix",
    title: "Ổn định",
    note: "Các lệnh quản lý thành viên ổn định hơn.",
  },
  {
    version: "0.8.10",
    date: "2026-06-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Bật tuỳ chọn mời ngoài tên miền đáng tin hơn.",
  },
  {
    version: "0.8.9",
    date: "2026-06-19",
    kind: "feature",
    title: "Hiệu năng",
    note: "Tận dụng tab ChatGPT sẵn có thay vì mở thêm tab mới.",
  },
  {
    version: "0.8.8",
    date: "2026-06-18",
    kind: "fix",
    title: "Thu hồi lời mời",
    note: "Tìm email bằng ô tìm kiếm, nhanh hơn cuộn danh sách.",
  },
  {
    version: "0.8.7",
    date: "2026-06-18",
    kind: "fix",
    title: "Ổn định",
    note: "Tìm email trong danh sách chính xác hơn.",
  },
  {
    version: "0.8.6",
    date: "2026-06-18",
    kind: "fix",
    title: "Mời thành viên",
    note: "Xác minh sau khi mời nhanh hơn nhiều.",
  },
  {
    version: "0.8.5",
    date: "2026-06-18",
    kind: "fix",
    title: "Hiệu năng",
    note: "Bắt đầu lệnh mời nhanh hơn.",
  },
  {
    version: "0.8.4",
    date: "2026-06-18",
    kind: "fix",
    title: "Ổn định",
    note: "Mọi lệnh đều có hạn giờ, không còn kẹt ở trạng thái đang chạy.",
  },
  {
    version: "0.8.3",
    date: "2026-06-17",
    kind: "fix",
    title: "Loại suất",
    note: "Đã đúng loại suất thì bỏ qua, không thao tác thừa.",
  },
  {
    version: "0.8.2",
    date: "2026-06-17",
    kind: "feature",
    title: "Đồng bộ",
    note: "Thêm nút đồng bộ riêng cho từng người đang chờ.",
  },
  {
    version: "0.8.1",
    date: "2026-06-17",
    kind: "fix",
    title: "Đồng bộ",
    note: "Workspace nhiều thành viên không còn bị đánh dấu đã gỡ oan.",
  },
  {
    version: "0.7.16",
    date: "2026-06-17",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Gỡ thành viên ổn định hơn và báo lỗi rõ ràng hơn.",
  },
  {
    version: "0.7.15",
    date: "2026-06-17",
    kind: "fix",
    title: "Mời thành viên",
    note: "Rút ngắn thời gian chờ khi xác minh lời mời.",
  },
  {
    version: "0.7.14",
    date: "2026-06-17",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Gỡ thành viên hoạt động đúng với giao diện tiếng Việt.",
  },
  {
    version: "0.7.13",
    date: "2026-06-17",
    kind: "feature",
    title: "Thu hồi lời mời",
    note: "Người đã nhận lời mời thì tự chuyển sang gỡ khỏi workspace.",
  },
  {
    version: "0.7.12",
    date: "2026-06-17",
    kind: "fix",
    title: "Mời thành viên",
    note: "Lệnh mời không còn kẹt lâu ở bước xác minh.",
  },
  {
    version: "0.7.11",
    date: "2026-06-17",
    kind: "fix",
    title: "Chu kỳ thanh toán",
    note: "Đọc được thêm cách viết ngày gia hạn của ChatGPT.",
  },
  {
    version: "0.7.10",
    date: "2026-06-17",
    kind: "fix",
    title: "Bảo trì",
    note: "Có bản mới là extension tự nạp lại ngay.",
  },
  {
    version: "0.7.9",
    date: "2026-06-16",
    kind: "chore",
    title: "Hiệu năng",
    note: "Rút ngắn thời gian chờ giữa hai lệnh.",
  },
  {
    version: "0.7.8",
    date: "2026-06-15",
    kind: "fix",
    title: "Bảo trì",
    note: "Bản cũ được phát hiện sớm, không chạy phí thời gian.",
  },
  {
    version: "0.7.7",
    date: "2026-06-15",
    kind: "fix",
    title: "Ổn định",
    note: "Tìm thành viên theo email chính xác hơn.",
  },
  {
    version: "0.7.5",
    date: "2026-06-15",
    kind: "fix",
    title: "Bảo trì",
    note: "Chỉ tự nạp lại khi thật sự có bản mới.",
  },
  {
    version: "0.7.4",
    date: "2026-06-15",
    kind: "fix",
    title: "Bảo trì",
    note: "Tự nạp lại khi extension còn chạy bản cũ.",
  },
  {
    version: "0.7.3",
    date: "2026-06-15",
    kind: "fix",
    title: "Loại suất",
    note: "Đổi loại suất đúng người hơn trong danh sách dài.",
  },
  {
    version: "0.7.2",
    date: "2026-06-15",
    kind: "fix",
    title: "Loại suất",
    note: "Đổi loại suất hoàn tất được cả khi cần xác nhận thêm.",
  },
  {
    version: "0.7.1",
    date: "2026-06-15",
    kind: "fix",
    title: "Loại suất",
    note: "Đọc được loại suất ở mọi cách hiển thị.",
  },
  {
    version: "0.7.0",
    date: "2026-06-15",
    kind: "feature",
    title: "Loại suất",
    note: "Thêm lệnh đổi loại suất cấp phép từ bảng điều khiển.",
  },
  {
    version: "0.6.19",
    date: "2026-06-15",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Gỡ thành viên không còn tìm sót ở danh sách dài.",
  },
  {
    version: "0.6.18",
    date: "2026-06-14",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ không còn đọc nhầm danh sách yêu cầu đang chờ.",
  },
  {
    version: "0.6.17",
    date: "2026-06-14",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ lời mời đọc đúng danh sách.",
  },
  {
    version: "0.6.16",
    date: "2026-06-14",
    kind: "fix",
    title: "Mời thành viên",
    note: "Lời mời không tới nơi thì gỡ khỏi bảng điều khiển.",
  },
  {
    version: "0.6.15",
    date: "2026-06-09",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ đọc hết danh sách dài nhiều trang.",
  },
  {
    version: "0.6.14",
    date: "2026-06-09",
    kind: "fix",
    title: "Đồng bộ",
    note: "Đồng bộ đọc được danh sách chia nhiều trang.",
  },
  {
    version: "0.6.13",
    date: "2026-05-21",
    kind: "chore",
    title: "Bảo trì",
    note: "Cải thiện bên trong, không đổi cách dùng.",
  },
  {
    version: "0.6.12",
    date: "2026-05-20",
    kind: "chore",
    title: "Bảo trì",
    note: "Cải thiện bên trong, không đổi cách dùng.",
  },
  {
    version: "0.6.11",
    date: "2026-05-20",
    kind: "fix",
    title: "Gỡ thành viên",
    note: "Gỡ đúng thành viên trong danh sách dài.",
  },
  {
    version: "0.6.10",
    date: "2026-05-20",
    kind: "chore",
    title: "Giao diện",
    note: "Đồng bộ giá chỉ chạy từ bảng điều khiển.",
  },
  {
    version: "0.6.7",
    date: "2026-05-20",
    kind: "fix",
    title: "Ổn định",
    note: "Báo lỗi rõ ràng hơn khi không chạy được trên trang ChatGPT.",
  },
  {
    version: "0.6.6",
    date: "2026-05-20",
    kind: "fix",
    title: "Mời thành viên",
    note: "Luôn tắt tuỳ chọn mời ngoài tên miền sau khi mời xong.",
  },
  {
    version: "0.6.5",
    date: "2026-05-20",
    kind: "fix",
    title: "Mời thành viên",
    note: "Lệnh mời chạy đúng trình tự hơn.",
  },
  {
    version: "0.6.4",
    date: "2026-05-20",
    kind: "fix",
    title: "Mời thành viên",
    note: "Xác minh nhanh hơn và không đánh dấu đã gỡ oan.",
  },
  {
    version: "0.6.3",
    date: "2026-05-20",
    kind: "fix",
    title: "Ổn định",
    note: "Tự mở lại tab mới khi tab cũ hỏng.",
  },
  {
    version: "0.6.2",
    date: "2026-05-20",
    kind: "fix",
    title: "Mời thành viên",
    note: "Danh sách cập nhật ngay sau khi gửi lời mời.",
  },
  {
    version: "0.6.1",
    date: "2026-05-20",
    kind: "fix",
    title: "Ổn định",
    note: "Sửa lỗi mỗi thao tác bị bấm thành hai lần.",
  },
  {
    version: "0.6.0",
    date: "2026-05-20",
    kind: "feature",
    title: "Mua suất",
    note: "Đi trọn chuỗi thanh toán khi mua thêm suất.",
  },
  {
    version: "0.5.1",
    date: "2026-05-20",
    kind: "feature",
    title: "Mua suất",
    note: "Đối chiếu số suất trước khi bấm nút trả tiền cuối.",
  },
  {
    version: "0.5.0",
    date: "2026-05-20",
    kind: "feature",
    title: "Mua suất",
    note: "Thêm lệnh mua thêm suất từ bảng điều khiển.",
  },
  {
    version: "0.4.20",
    date: "2026-05-19",
    kind: "fix",
    title: "Ổn định",
    note: "Dữ liệu cập nhật ngay sau mỗi lệnh.",
  },
  {
    version: "0.4.19",
    date: "2026-05-19",
    kind: "fix",
    title: "Đếm suất",
    note: "Đọc được số suất khi đang dùng vượt hạn mức.",
  },
  {
    version: "0.4.18",
    date: "2026-05-19",
    kind: "fix",
    title: "Ổn định",
    note: "Tự mở lại tab mới khi tab hỏng.",
  },
  {
    version: "0.4.17",
    date: "2026-05-19",
    kind: "fix",
    title: "Ổn định",
    note: "Tự tải lại tab ChatGPT khi không nạp được vào trang.",
  },
  {
    version: "0.4.16",
    date: "2026-05-19",
    kind: "feature",
    title: "Giao diện",
    note: "Gọn lại ô chọn vai trò và thêm nút làm mới số suất.",
  },
  {
    version: "0.4.15",
    date: "2026-05-19",
    kind: "fix",
    title: "Vai trò",
    note: "Đổi vai trò không còn treo theo giao diện mới của ChatGPT.",
  },
  {
    version: "0.4.14",
    date: "2026-05-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Không xác minh được email nào thì báo hỏng.",
  },
  {
    version: "0.4.13",
    date: "2026-05-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Bảng điều khiển chỉ hiện email ChatGPT thật sự nhận.",
  },
  {
    version: "0.4.12",
    date: "2026-05-19",
    kind: "feature",
    title: "Giao diện",
    note: "Cửa sổ extension hiện lệnh đang chạy kèm thanh tiến độ.",
  },
  {
    version: "0.4.11",
    date: "2026-05-19",
    kind: "fix",
    title: "Ngôn ngữ",
    note: "Sửa nhãn giao diện là extension nhận ngay.",
  },
  {
    version: "0.4.10",
    date: "2026-05-19",
    kind: "feature",
    title: "Mời thành viên",
    note: "Chỉ ghi nhận lời mời đã có trong danh sách chờ.",
  },
  {
    version: "0.4.9",
    date: "2026-05-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Không còn kẹt sau khi bật mời ngoài tên miền.",
  },
  {
    version: "0.4.8",
    date: "2026-05-19",
    kind: "feature",
    title: "Mời thành viên",
    note: "Lấy danh sách lời mời đang chờ về bảng điều khiển sau khi mời.",
  },
  {
    version: "0.4.7",
    date: "2026-05-19",
    kind: "fix",
    title: "Ổn định",
    note: "Đọc email chính xác hơn và chạy nhanh hơn.",
  },
  {
    version: "0.4.6",
    date: "2026-05-19",
    kind: "fix",
    title: "Ngôn ngữ",
    note: "Báo rõ khi ChatGPT đang dùng ngôn ngữ khác.",
  },
  {
    version: "0.4.5",
    date: "2026-05-19",
    kind: "fix",
    title: "Giao diện",
    note: "Tiến trình lệnh mời hiện chi tiết hơn.",
  },
  {
    version: "0.4.4",
    date: "2026-05-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Nhập được nhiều email theo giao diện mới của ChatGPT.",
  },
  {
    version: "0.4.3",
    date: "2026-05-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Tìm tuỳ chọn mời ngoài tên miền bền hơn và báo rõ khi hết suất.",
  },
  {
    version: "0.4.2",
    date: "2026-05-19",
    kind: "fix",
    title: "Mời thành viên",
    note: "Chọn đúng tuỳ chọn cho phép lời mời ngoài tên miền.",
  },
  {
    version: "0.4.1",
    date: "2026-05-18",
    kind: "fix",
    title: "Ổn định",
    note: "Luôn quay về trang thành viên sau mỗi lệnh.",
  },
  {
    version: "0.4.0",
    date: "2026-05-18",
    kind: "feature",
    title: "Ngôn ngữ",
    note: "Tự tạo lời mời thử để thu thập nhãn giao diện khi danh sách trống.",
  },
  {
    version: "0.3.2",
    date: "2026-05-18",
    kind: "fix",
    title: "Ngôn ngữ",
    note: "Thu thập nhãn giao diện báo tiến trình sớm hơn.",
  },
  {
    version: "0.3.1",
    date: "2026-05-18",
    kind: "fix",
    title: "Ngôn ngữ",
    note: "Thu thập nhãn giao diện có tiến trình và hạn giờ rõ ràng.",
  },
  {
    version: "0.3.0",
    date: "2026-05-18",
    kind: "feature",
    title: "Ngôn ngữ",
    note: "Tự đọc nhãn giao diện của một ngôn ngữ từ trang quản trị.",
  },
  {
    version: "0.2.0",
    date: "2026-05-18",
    kind: "feature",
    title: "Ngôn ngữ",
    note: "Hiệu chỉnh nhãn giao diện và tự chữa khi nhãn cũ không còn đúng.",
  },
  {
    version: "0.1.0",
    date: "2026-05-18",
    kind: "feature",
    title: "Bản đầu tiên",
    note: "Bản phát hành đầu tiên của extension.",
  },
];
