"""số thứ tự ghi tăng đơn điệu cho wallet_transactions (seq)

Revision ID: 0043_wallet_txn_seq
Revises: 0042_email_otp
Create Date: 2026-07-17

Lỗi hiển thị: nhiều giao dịch ví tạo trong CÙNG 1 request (vd nạp-qua-hoá-đơn +
trừ phí mời) chia sẻ y hệt `created_at` (func.now() = mốc bắt đầu transaction).
Endpoint sắp xếp `created_at DESC, id DESC` mà `id` là uuid4 NGẪU NHIÊN → thứ tự
các dòng cùng mốc bị loạn → số dư "Còn" (balance_after) đọc không khớp thời gian.

Fix: thêm cột `seq` IDENTITY (tăng đơn điệu theo thứ tự ghi) làm khoá sắp xếp.
Backfill dòng cũ theo (created_at, ctid) — ctid ≈ thứ tự vật lý/ghi cho sổ cái
append-only, khôi phục gần đúng trình tự cho các dòng cùng mốc thời gian.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0043_wallet_txn_seq"
down_revision: Union[str, None] = "0042_email_otp"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # 1) Thêm cột tạm nullable rồi backfill theo thứ tự vật lý (ctid) trong toàn bảng,
    #    ưu tiên created_at để nhất quán với dữ liệu hiện có.
    op.add_column("wallet_transactions", sa.Column("seq", sa.BigInteger(), nullable=True))
    conn.execute(
        sa.text(
            """
            WITH ordered AS (
                SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, ctid) AS rn
                FROM wallet_transactions
            )
            UPDATE wallet_transactions t
            SET seq = o.rn
            FROM ordered o
            WHERE t.id = o.id
            """
        )
    )
    op.alter_column("wallet_transactions", "seq", nullable=False)

    # 2) Chuyển seq thành cột IDENTITY (BY DEFAULT) rồi đẩy sequence qua max hiện có
    #    để dòng mới tiếp tục tăng không đụng giá trị đã backfill.
    conn.execute(
        sa.text(
            "ALTER TABLE wallet_transactions "
            "ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY"
        )
    )
    conn.execute(
        sa.text(
            "SELECT setval(pg_get_serial_sequence('wallet_transactions', 'seq'), "
            "COALESCE((SELECT MAX(seq) FROM wallet_transactions), 0) + 1, false)"
        )
    )

    op.create_index("ix_wallet_transactions_seq", "wallet_transactions", ["seq"])


def downgrade() -> None:
    op.drop_index("ix_wallet_transactions_seq", table_name="wallet_transactions")
    op.drop_column("wallet_transactions", "seq")
